# Generated by Django 3.1.4 on 2021-04-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('subject', models.CharField(max_length=30)),
                ('message', models.TextField(default='')),
                ('reply', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('replied_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': (('manage_inquiries_and_feedbacks', 'Can manage inquiries and feedbacks'),),
            },
        ),
    ]
