# Generated by Django 3.1.4 on 2021-04-17 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('description', models.TextField(default='')),
                ('duration', models.PositiveIntegerField(default='12', validators=[django.core.validators.MinValueValidator(1)])),
                ('fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
    ]
