# Generated by Django 3.1.4 on 2021-04-17 17:03

import Member.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('phone', models.CharField(max_length=10)),
                ('image1', models.ImageField(blank=True, default=' ', null=True, upload_to=Member.models.upload_member_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_expired', models.BooleanField(default=False)),
                ('expiry_at', models.DateField()),
                ('brought_at', models.DateTimeField(auto_now_add=True)),
                ('mem_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plans.plans')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.member')),
            ],
        ),
    ]
